### ISSUE TITLE
Añadir un nuevo párrafo descriptivo

### ISSUE THREAD

**Issue by Sherna0303** [Sherna0303/Basic-Web#1]
Añadiremos un nuevo párrafo debajo del párrafo inicial para proporcionar información adicional sobre la página. Este párrafo describirá el propósito de la página y cómo se utilizarán los issues para mejorarla. El párrafo será estilizado con un tamaño de fuente ligeramente menor y un color diferente para diferenciarlo del primer párrafo.

**Comment by jhona-esteban** [comment]
Cree la rama de develop y agregue los cambios
