### ISSUE TITLE
Añadir una lista de elementos

### ISSUE THREAD

**Issue by Sherna0303** [Sherna0303/Basic-Web#3]
Incorporaremos una lista no ordenada con varios elementos debajo del encabezado secundario. Esta lista demostrará cómo se pueden estructurar y presentar múltiples elementos relacionados de forma clara y organizada. Los elementos de la lista estarán estilizados con un tipo de lista específico (en este caso, cuadrados) y un color coherente con el resto de la página.

**Comment by jhona-esteban** [comment]
Agregue los cambios a la rama develop
